### ISSUE TITLE
CMake Error at libraries/CMakeLists.txt:573 (message)

### ISSUE THREAD

**Issue by Korilakkuma** [spotify/NFDecoder#5]
Maybe, it is required to install `gyp`.
Therefore, I think that it is better to add how to install `gyp` to README.

**Comment by 8W9aG** [comment]
You are right, I am adding a INCLUDE_UDT which can set to no if you want to skip this step (I certainly do in some projects).

**Comment by 8W9aG** [comment]
https://github.com/spotify/NFDecoder/pull/10
